return {
PlaceObj('ModItemCode', {
	'name', "tweaks",
	'comment', "yay tweaks",
	'FileName', "Code/tweaks.lua",
}),
PlaceObj('ModItemOptionNumber', {
	'name', "Construction",
	'comment', "BuildingConstructed",
	'DisplayName', "Building Constructed Chance",
	'Help', "Chance for a StoryBit that is triggered when a building is constructed to start.",
	'DefaultValue', 5,
}),
PlaceObj('ModItemOptionNumber', {
	'name', "Disasters",
	'comment', "Disasters",
	'DisplayName', "Disasters",
	'Help', "Chance for a StoryBit that is triggered by disasters to start.",
	'DefaultValue', 25,
}),
PlaceObj('ModItemOptionNumber', {
	'name', "ExRocket",
	'comment', "ExperimentalRocketLaunched",
	'DisplayName', "Experimental Rocket Launch Chance",
	'Help', "Chance for a StoryBit that is triggered when an experimental rocket is launched to start.",
	'DefaultValue', 10,
}),
PlaceObj('ModItemOptionNumber', {
	'name', "FoundersLanded",
	'comment', "FounderRocketLanded",
	'DisplayName', "Founder Rocket Landed Chance",
	'Help', "Chance for a StoryBit that is triggered when the founders land on Mars to start.",
	'DefaultValue', 5,
}),
PlaceObj('ModItemOptionNumber', {
	'name', "Prefab",
	'comment', "PlacePrefab",
	'DisplayName', "Place Prefab Chance",
	'Help', "Chance for a StoryBit that is triggered when a prefab is placed to start.",
	'DefaultValue', 5,
}),
PlaceObj('ModItemOptionNumber', {
	'name', "Rivals",
	'comment', "Rivals",
	'DisplayName', "Rivals",
	'Help', "Chance for a StoryBit that is triggered by rivals to start.",
	'DefaultValue', 10,
}),
PlaceObj('ModItemOptionNumber', {
	'name', "Rockets",
	'comment', "Rockets",
	'DisplayName', "Rocket Event Chance",
	'Help', "Chance for a StoryBit that is triggered when a rocket attempts to takeoff, land, or unload on Mars to start.",
	'DefaultValue', 20,
}),
PlaceObj('ModItemOptionNumber', {
	'name', "SanityBreakdown",
	'comment', "SanityBreakdown",
	'DisplayName', "Sanity Breakdown Chance",
	'Help', "Chance for a StoryBit that is triggered when a colonist has a sanity breakdown to start.",
	'DefaultValue', 10,
}),
PlaceObj('ModItemOptionNumber', {
	'name', "TechResearched",
	'comment', "TechResearched",
	'DisplayName', "Tech Researched Chance",
	'Help', "Chance for a StoryBit that is triggered when a new tech is researched to start.",
	'DefaultValue', 5,
}),
PlaceObj('ModItemOptionNumber', {
	'name', "Terraform",
	'comment', "Terraforming",
	'DisplayName', "Terraforming",
	'Help', "Chance for a Terraforming StoryBit that is triggered automatically based on a random chance to start.",
	'DefaultValue', 5,
}),
PlaceObj('ModItemOptionNumber', {
	'name', "Tick",
	'comment', "Tick (Others)",
	'DisplayName', "Others",
	'Help', "Chance for a StoryBit that is triggered automatically based on a random chance to start.",
	'DefaultValue', 5,
}),
}
