return PlaceObj('ModDef', {
	'title', "All The Stories!",
	'description', "Pending...",
	'image', "Images/thumbnail.png",
	'last_changes', "https://github.com/Surviving-Mars-Mods/All-The-Stories/blob/master/changelog.md",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"*.idea/*",
		"*src/*",
		"*.gitignore",
		"*.iml",
		"Info/2do.txt",
	},
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "FIZZLE1",
			'title', "Fizzle Fuze's Library",
			'version_major', 1,
			'version_minor', 5,
		}),
	},
	'id', "FIZZLE2",
	'steam_id', "2730719659",
	'pops_desktop_uuid', "7c6919ad-e58c-4e8b-92cd-8f58ee0017f7",
	'pops_any_uuid', "216adac3-35c0-44da-87e4-077f6b196b1a",
	'author', "Fizzle_Fuze",
	'version_major', 1,
	'version_minor', 2,
	'version', 69,
	'lua_revision', 1009413,
	'saved_with_revision', 1010784,
	'code', {
		"Code/tweaks.lua",
	},
	'has_options', true,
	'saved', 1643064143,
	'TagGameplay', true,
	'TagOther', true,
})